apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-db-instance.clsm0yg4ca5a.us-east-2.rds.amazonaws.com:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-db-instance.clsm0yg4ca5a.us-east-2.rds.amazonaws.com:3306/foodcataloguedb
  userdb_url: jdbc:mysql://mysql-db-instance.clsm0yg4ca5a.us-east-2.rds.amazonaws.com:3306/userdb
  orderdb_url: mongodb+srv://admin:admin123@atlas-foodapp-cluster.puk4cpe.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka